# Generated by Django 2.1.5 on 2020-02-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200215_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='websit',
            new_name='website',
        ),
    ]
